include:
  - local: 'ci/common.yml'
  - local: 'ci/build.yml'
  - local: 'ci/deploy.yml'

default-build:
  stage: build
  script:
    - echo "Nothing to build"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
