[tools]
node = "24.14.1"
pnpm = "10.33.0"
"npm:@tikui/cli" = "3.2.0"

[tasks.setup]
run = "pnpm -r install"

[tasks.setup-claude-code]
run = "ln -sfn .agents .claude && ln -sf ./AGENTS.md ./CLAUDE.md"

[tasks.setup-github-copilot]
run = '''
mkdir -p .github
ln -sfn ../.agents/agents .github/agents
ln -sfn ../.agents/skills .github/skills
'''

[tasks.build]
run = "pnpm build"

[tasks.dev]
run = "pnpm dev"

[tasks.lint]
run = "pnpm lint"

[tasks.lint-ci]
run = "pnpm lint:ci"

[tasks.format]
run = "pnpm format"

[tasks.format-ci]
run = "pnpm format:ci"

[tasks.test-unit]
run = "pnpm test:unit"

[tasks.test-unit-ci]
run = "pnpm test:unit:ci"

[tasks.styles-dev]
run = "pnpm --filter styles dev"

[tasks.styles-lint]
run = "pnpm --filter styles lint"

[tasks.styles-test-unit-ci]
run = "pnpm --filter styles test:unit:ci"

[tasks.react-lint]
run = "pnpm --filter react lint"

[tasks.react-test-unit-ci]
run = "pnpm --filter react test:unit:ci"

[tasks.icons-build]
run = "pnpm --filter icons build"

[tasks.styles-create-component]
dir="styles"
description="Create a style components using Tikui CLI"
usage = '''
arg "<component>" help="Name of the component to create in lower kebab-case"
flag "--path <path>" help="Path to create the component in, relative to src, default atom" default="atom"
'''
run='''
tikui create -p ippon ${usage_component} src/${usage_path}
'''
