styles-build:
  extends:
    - .common-pnpm-build
  needs: ['icons-build']
  script:
    - pnpm --filter styles lint:ci
    - pnpm --filter styles test:unit:ci
    - pnpm --filter styles build
  artifacts:
    paths:
      - styles/dist/
    expire_in: 2 hours
