name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          # renovate: datasource=node-version depName=node
          node-version: 24.14.1
          cache: pnpm
      - run: pnpm -r install --frozen-lockfile
      - run: pnpm format:ci
      - run: pnpm lint:ci
      - run: pnpm test:unit:ci
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            icons/dist
            icons/types
            styles/dist
            react/dist
          retention-days: 1

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          # renovate: datasource=node-version depName=node
          node-version: 24.14.1
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - run: pnpm -r install --frozen-lockfile
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - run: pnpm -r publish --access public --no-git-checks

  status-checks:
    name: status-checks
    needs: [build]
    permissions:
      contents: none
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Validation Status checks
        run: |
          echo '${{ toJSON(needs) }}'
          if [[ (('skipped' == '${{ needs.build.result }}') || ('success' == '${{ needs.build.result }}')) ]]; then
            exit 0
          fi
          exit 1
